VERSION=1.0.0

GO_FILES:=$(shell find . -type f -name '*.go')

run: bitcly
	./bitcly

bitcly: $(GO_FILES)
	go build -o ./bitcly

clean:
	rm -rf bitcly
	go clean -cache -testcache -modcache

test:
	go test -p 8 -cover --timeout 1m -race ./...